##########################
# Моя первая автоматизация через Гитхаб Экшнс
##########################
name: My-First-Actions

on: [push]

jobs:
  my_testing:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: run a multi-line script
      run:
        echo Another line,
        echo as you want!
        
  
