##########################
# Моя первая автоматизация через Гитхаб Воркфлоу
##########################
name: My-First-Workflow
env:
  APP_NAME: "MyFlask"
  PACKAGE_NAME: "flask_deploy_ver-${{ github.sha }}"

on:
  push:
    branches:
      - master

jobs:
  my_testing:
    runs-on: ubuntu-latest
    steps:
      - name: print info
        run: uname -a
      - name: print Hello World
        run: echo "Hello World from testing job!"
      - name: print package name
        run: echo "package name is ${{ env.PACKAGE_NAME }}"
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    steps:
      - name: Execute commands
        run: |
          echo "Message one"
          echo "Message two"
          echo "App name is ${{ env.APP_NAME }}"
      - name: print greetings
        run: echo "Thanks for deployment!"
      - name: list current folder before copying
        run: ls -la
      - name: Copying files from git
        uses: acting/checkout@v1
      - name: list current folder after copying
        run: ls -la
      - name: check is AWS available
        run: aws --version
      - name: Check ZIP
        run: zip