##########################
# Моя первая автоматизация через Гитхаб Воркфлоу
##########################
name: My-First-Workflow

on: 
  push:
    branches:
      - master

jobs:
  my_testing:
    runs-on: ubuntu-latest
    steps:
      - name: print Hello World
        run: echo "Hello World!" 
    
  
  my_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: print greetings
        run: echo "Thanks for deployment!"


        
  
