##########################
# Моя первая автоматизация через Гитхаб Воркфлоу
##########################
name: My-First-Workflow
env:
  APP_NAME: "MyFlask"
  PACKAGE_NAME: "flask_deploy_ver-${{ github.sha }}"

on:
  push:
    branches:
      - master

jobs:
  
  my_testing:
    runs-on: ubuntu-latest
    env:
      var1: "Job My_Testing var1"
      var2: "Job My_Testing var2"
    steps:
      - name: Execute commands
        run: |
          echo "var1 is ${{ env.var1 }}"
          echo "var2 is ${{ env.var2 }}"
          echo "Message two at ${{ GITHUB_JOB }}"
          echo "App name is ${{ env.APP_NAME }}"
      - name: print info
        run: uname -a
      - name: print Hello World
        run: echo "Hello World from testing job!"
      - name: print package name
        run: echo "package name is ${{ env.PACKAGE_NAME }}"
  
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    env:
      var1: "Job My_deploy var1"
      var2: "Job My_deploy var2"
    steps:
      - name: Execute commands
        run: |
          echo "var1 is ${{ env.var1 }}"
          echo "var2 is ${{ env.var2 }}"
          echo "Message two at ${{ GITHUB_JOB }}"
          echo "App name is ${{ env.APP_NAME }}"
      - name: print greetings
        run: echo "Thanks for deployment!"
      - name: list current folder before copying
        run: ls -la
      - name: Copying files from git
        uses: actions/checkout@v1
      - name: list current folder after copying
        run: ls -la
      - name: check is AWS available
        run: aws --version
      - name: Check ZIP
        run: zip --version